done: gracefull shutdown (инкремент 23)
pinbrain/urlshortener pull request #22
Opened 2024-09-14 11:57 UTC by pinbrain

2024-09-17 22:46 UTC, avhitrov requested changes
Практически все реализовано отлично. Есть одна не охваченная мягким шатдауном операция. В комментариях к коду.

2024-09-17 22:46 UTC, avhitrov commented on internal/storage/pg_url.go
>  	close(db.urlDelCh)
Есть одно маленькое "но". В момент закрытия канала в памяти вполне может болтаться с десяток горутин `DeleteUserURLs`, которые будут пытаться в этот канал писать данные. В итоге вместо асинхронного удаления получим ряд паник от данных функций. Прежде, чем закрывать хранилище (но после остановки веб-сервиса) необходимо дождаться завершения данных горутин.

2024-09-18 17:04 UTC, pinbrain commented
Реализовал метод Close для хендлера, где ожидается завершение всех goroutines

2024-09-20 21:41 UTC, avhitrov approved these changes
Годно. Аппрув!

2024-09-23 11:49 UTC, merged